export enum CatalogoEnum {
  ESTATUS_USUARIO = 1,
  SEXO = 2,
  TIPO_ESCOLAR = 3,
  TURNO_ALUMNO = 4,
  TIPO_USUARIO = 5,
  CARRERAS_EDUCATIVAS = 6,
  ESTADO_FISICO_LIBRO = 7,
  IDIOMA = 8,
  ESTATUS_LIBRO = 9,
  ESTATUS_PRESTAMOS = 10,
}
